Suppoort all CAPI CRD API versions
giantswarm/kyverno-policies pull request #188
Opened 2022-01-18 15:26 UTC by AverageMarcus

Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>

### Checklist

- [x] Update changelog in CHANGELOG.md.

2022-01-18 15:29 UTC, whites11 approved these changes
wow, LGTM

2022-01-18 16:03 UTC, njuettner approved these changes
lgtm 🙂

2022-01-18 16:04 UTC, tfussell requested changes
Please ensure that these policies don't affect Kyverno on clusters that don't have `v1alpha4` or `v1beta1` defined. Also I recommend restarting Kyverno after updating the policies and checking the logs to see if there are any warnings or non-apparent errors.

2022-01-19 10:23 UTC, AverageMarcus commented
> Please ensure that these policies don't affect Kyverno on clusters that don't have `v1alpha4` or `v1beta1` defined. Also I recommend restarting Kyverno after updating the policies and checking the logs to see if there are any warnings or non-apparent errors.

There's some errors when applying the policy manifest, but the errors are just more of some we already have for other policies. (They're more warnings in my opinion)
There's no errors/warnings when a policy is being applied to a resource.

2022-01-19 10:25 UTC, AverageMarcus commented on helm/policies-aws/templates/AWSCAPI.yaml
> +        - infrastructure.cluster.x-k8s.io/v1beta1/AWSCluster
Confirmed that all the AWS and Azure types we reference have a `v1beta1` version in the latest release. There are a small number of CRDs that don't have a `v1beta1` (such as `AWSManagedCluster`) but we don't use these anyway.

2022-01-19 10:46 UTC, tfussell approved these changes

2022-01-19 10:47 UTC, merged